### ISSUE TITLE
Feature: send e-mail on any status change

### ISSUE THREAD

**Issue by pva** [chantra/redmine_newissuealerts#1]
Is it possible to change e-mail on any status change? Suppose I have three statuses and associated mail groups: 

Translation - translators@domain
Editing       - editors@domain
Commit       - developers@domain

Now I want if status changes corresponding groups received e-mail. So if I created ticket with status translation translators@domain got mail, if I changed status to Editing both translators@domain and editors@domain got status update message. Is it hard thing to do?

**Comment by chantra** [comment]
Hi,

sorry for that late reply.
I like the idea but unfortunately, I dont have the bandwodth to work on that. Plus, my knowledge of ruby being low, it would take me quite some time to get this working.

Anyhow, if you get this to work, please let me know through github and I will merge the feature in.
tks

**Comment by kishorej** [comment]
I tried to run the "rake db:migrate:plugins RAILS_ENV=production" and getting the below error.

rake aborted!
An error has occurred, this and all later migrations canceled:

PGError: ERROR:  current transaction is aborted, commands ignored until end of transaction block
: INSERT INTO schema_migrations (version) VALUES ('1-redmine_issues_group')
