### ISSUE TITLE
Compatibility with latest Redmine

### ISSUE THREAD

**Issue by dabrahams** [chantra/redmine_newissuealerts#10]
Is this plugin compatible with 1.2?  If so, could you please update its description page at http://www.redmine.org/plugins?

Thanks

**Comment by chantra** [comment]
hi, I believe it is with redmine 1.0. while I cannot test it on 1.2 I would appreciate if you could test by yourself and report back.

**Comment by jbutz** [comment]
It works on 1.2. I have made a few modifications to fix problems and support private issues: https://github.com/jbutz/redmine_newissuealerts

**Comment by dabrahams** [comment]
Using @jbutz's modifications, I am seeing a small problem: https://gist.github.com/1090351#file_nia.png

**Comment by jbutz** [comment]
Hm, I don't see how my changes should have affected that. They could have been pre-existing.

**Comment by chantra** [comment]
actually, these localized items should have been taken from redmine core's localization files. can't remember on top of my head where those are.

@jbutz, there is 2 localization files because redmine 0.8 used to use lang/\* while redmine 0.9 onward uses config/locales/\* and a new file syntax.
I plan to retire support for 0.8 in next release.

**Comment by jbutz** [comment]
@chantra, Ah, that makes more sense now.

**Comment by dabrahams** [comment]
So, err... what should I do?

**Comment by chantra** [comment]
it is just a localization error, you might just want to use he plugin as is.

**Comment by chantra** [comment]
try latest master code, jbutz change is somehow included, support for redmine 0.8 removed and I fixed the %s issue.

**Comment by chantra** [comment]
Ok, localization issue was due to http://www.redmine.org/issues/8554

Fixed in 1.2.1, so, if you upgrade, your issue will be gone.

Pls, let me know how latest master version goes.
I believe this issue could be closed.

**Comment by chantra** [comment]
closing issue as plugin is compatible and localization issue is a redmine issue and not a plugin issue
