### ISSUE TITLE
Getting 500 internal server error when creating new issues. 

### ISSUE THREAD

**Issue by isqrd** [chantra/redmine_newissuealerts#2]
I'm running redmine 0.8.7, ruby 1.8.7, and Rails 2.2.2, after installing the latest newissuealerts I get an internal 500 server error, and the following log message.  The issue is created, but no email is sent.   

ActionView::TemplateError (undefined method `author' for nil:NilClass) on line #5 of vendor/plugins/redmine_newissuealerts/app/views/newissuealerts_mailer/newissuealert.text.plain.rhtml:
2: if l(:this_is_gloc_lib) == 'this_is_gloc_lib'
3:   l(:text_issue_added, "##{@issue.id}", @issue.author)
4: else
5:   l(:text_issue_added, :id => "##{@issue.id}", :author => @issue.author)
6: end
7: %>
8:

```
vendor/plugins/redmine_newissuealerts/app/views/newissuealerts_mailer/newissuealert.text.plain.rhtml:5
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/renderable.rb:39:in `send'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/renderable.rb:39:in `render'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/template.rb:73:in `render_template'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_view/base.rb:256:in `render'
/usr/lib64/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:564:in `render'
app/models/mailer.rb:344:in `body'
/usr/lib64/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:642:in `create_mail'
app/models/mailer.rb:327:in `create_mail'
/usr/lib64/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:512:in `create!'
/usr/lib64/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:455:in `initialize'
/usr/lib64/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:392:in `new'
/usr/lib64/ruby/gems/1.8/gems/actionmailer-2.2.2/lib/action_mailer/base.rb:392:in `method_missing'
vendor/plugins/redmine_newissuealerts/lib/redmine_newissuealerts/issue_patch.rb:45:in `newissue_created'
vendor/plugins/redmine_newissuealerts/lib/redmine_newissuealerts/issue_patch.rb:43:in `each'
vendor/plugins/redmine_newissuealerts/lib/redmine_newissuealerts/issue_patch.rb:43:in `newissue_created'
vendor/plugins/redmine_newissuealerts/lib/redmine_newissuealerts/issue_patch.rb:41:in `each'
vendor/plugins/redmine_newissuealerts/lib/redmine_newissuealerts/issue_patch.rb:41:in `newissue_created'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `send'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:166:in `call'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:93:in `run'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:92:in `each'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:92:in `send'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:92:in `run'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:277:in `run_callbacks'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:315:in `callback'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:238:in `create_without_timestamps'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/timestamp.rb:29:in `create'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:2699:in `create_or_update_without_callbacks'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/callbacks.rb:222:in `create_or_update'
```

 /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:2383:in `save_without_validation'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/validations.rb:1009:in`save_without_dirty'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/dirty.rb:79:in `save_without_transactions'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:179:in`send'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:179:in `with_transaction_returning_status'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in`transaction'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:129:in `transaction'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:138:in`transaction'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:178:in `with_transaction_returning_status'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:146:in`save'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:158:in `rollback_active_record_state!'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/transactions.rb:146:in`save'
    app/controllers/issues_controller.rb:157:in `new'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in`send'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in `perform_action_without_filters'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:617:in`call_filters'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
    /usr/lib64/ruby/1.8/benchmark.rb:293:in `measure'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/rescue.rb:136:in `perform_action_without_caching'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/caching/sql_cache.rb:13:in`perform_action'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    /usr/lib64/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/query_cache.rb:8:in`cache'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/caching/sql_cache.rb:12:in `perform_action'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:524:in`send'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:524:in `process_without_filters'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:606:in`process_without_session_management_support'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/session_management.rb:134:in `process'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:392:in`process'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:183:in `handle_request'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:110:in`dispatch_unlocked'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:123:in `dispatch'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:122:in`synchronize'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:122:in `dispatch'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:132:in`dispatch_cgi'
    /usr/lib64/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/dispatcher.rb:39:in `dispatch'
    /usr/lib64/ruby/gems/1.8/gems/rails-2.2.2/lib/webrick_server.rb:103:in`handle_dispatch'
    /usr/lib64/ruby/gems/1.8/gems/rails-2.2.2/lib/webrick_server.rb:74:in `service'
    /usr/lib64/ruby/1.8/webrick/httpserver.rb:104:in`service'
    /usr/lib64/ruby/1.8/webrick/httpserver.rb:65:in `run'
    /usr/lib64/ruby/1.8/webrick/server.rb:173:in`start_thread'
    /usr/lib64/ruby/1.8/webrick/server.rb:162:in `start'
    /usr/lib64/ruby/1.8/webrick/server.rb:162:in`start_thread'
    /usr/lib64/ruby/1.8/webrick/server.rb:95:in `start'
    /usr/lib64/ruby/1.8/webrick/server.rb:92:in`each'
    /usr/lib64/ruby/1.8/webrick/server.rb:92:in `start'
    /usr/lib64/ruby/1.8/webrick/server.rb:37:in`start'
    /usr/lib64/ruby/1.8/webrick/server.rb:82:in `start'
    /usr/lib64/ruby/gems/1.8/gems/rails-2.2.2/lib/webrick_server.rb:60:in`dispatch'
    /usr/lib64/ruby/gems/1.8/gems/rails-2.2.2/lib/commands/servers/webrick.rb:66
    /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    /usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/dependencies.rb:153:in `require'
    /usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/dependencies.rb:521:in`new_constants_in'
    /usr/lib64/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/dependencies.rb:153:in `require'
    /usr/lib64/ruby/gems/1.8/gems/rails-2.2.2/lib/commands/server.rb:49
    /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    script/server:3

Rendering /var/www/htdocs/redmine/public/500.html (500 Internal Server Error)

**Comment by chantra** [comment]
hum, I have just oushed a change, can you check if it make a d=ifference pls.

**Comment by isqrd** [comment]
Hi. Thanks for looking into this. I'm still getting the same error. However, I did find it works if I uncheck plain text email only in the email notification settings, so I'm not too worried about it at the moment.

**Comment by chantra** [comment]
weird, the error is triggered by the PLAIN email part :s

**Comment by chantra** [comment]
Hi isrd,

Did you find a solution to this?

**Comment by chantra** [comment]
closing as there is no update
