### ISSUE TITLE
How to remove and address once it's in the list?

### ISSUE THREAD

**Issue by ihorne** [chantra/redmine_newissuealerts#3]
Whenever I hit edit/remove link I receive "Page not found".  How to get around this.

Thank you for your efforts.

**Comment by chantra** [comment]
Hi,

Sorry for the late reply.
Did you find a workaround to this?
It works fine for me using redmine-0.8.4, ruby 4.2, rubygems1.2

**Comment by chantra** [comment]
well, closing this as there were no update for a long time
