### ISSUE TITLE
Subprojects notification

### ISSUE THREAD

**Issue by softjuraj** [chantra/redmine_newissuealerts#4]
If I have created the "email on new issue" on parent project and somebody created new issue in some of its subprojects - No notification will come.
The notification should come also from subprojects New Issues. Or there could be checkbox if notification should be sent also from subprojects.

**Comment by chantra** [comment]
Hi softjuraj,

I am afraid the feature does not exist and I am a real ruby noob so it would take me ages to get this done.
Anyhow, if you can get this to work, please let me know and I will merge it into main trunk.

Will close this issue for now, please post any update here.
Tks
