### ISSUE TITLE
set "high importance" for notification mails

### ISSUE THREAD

**Issue by bstuycke** [chantra/redmine_newissuealerts#6]
We use this plugin for our support projects. Our customers will issue new tickets in these projects and we get notified.
This works fine, only problem is that the new issue alert mails look exactly like other notifications from Redmine. Obviously tickets from customers have higher priority than internal tickets.
Hence proposal: would it be possible to send the new issue alert mails with "High Importance" ?

**Comment by chantra** [comment]
Hi,

Thats a good idea, well, being able to configure it depending on project will be better.
Unfortunately, these days I am really busy with my day to day work and dont have any bandwidth available.

A patch would be welcome though ;)

**Comment by bstuycke** [comment]
I wish I knew better to program in Ruby and understand the redmine coding better.  It's quite a jungle for me.
However I did spent some time on it and found a good enough solution for me.

In newissuealerts_mailer.rb, I added headers "X-Priority" => 1.  

Of course all mails will now be sent with high importance, but that's ok for me.

For extending the GUI, I don't understand the code.

**Comment by chantra** [comment]
i will check into it one of those days.... but i really dont know when :s

**Comment by chantra** [comment]
Solved in a4786b650fc3fe3a38ef
