### ISSUE TITLE
Incorrect text/plain MIME part

### ISSUE THREAD

**Issue by whitequark** [chantra/redmine_newissuealerts#8]
The MIME part with type text/plain is generated with HTML tags inside, like this: http://pastebin.com/eDjVxwY8 (beware, it's kinda russian inside, so you need utf8).

Also, I think there should be a way to disable HTML mail completely. It's not very popular among software developers anyway, and I don't think much of them will want to see it in a mailing list (like I do).

**Comment by chantra** [comment]
Hi,

Tks for reporting it.

This is fixed in commit db8d0394bc099e5bbcd30ee68f05fa19650da357
Regarding the plain tex only, you might want to set it in redmine settings itself.
