### ISSUE TITLE
Mailman holds messages

### ISSUE THREAD

**Issue by whitequark** [chantra/redmine_newissuealerts#9]
Mailman holds messages sent to list with reason "Message has implicit destination". That's because you do not put To: header in it. See also http://mail.python.org/pipermail/mailman-users/2000-December/008259.html

**Comment by chantra** [comment]
Please also uncheck BCC in /settings/edit?tab=notifications

Does that fix it?

**Comment by chantra** [comment]
Closing this issue has outdated.

Unchecking BCC seems to do the job anyway
